### PR TITLE
DENG-3248: Multi app deployment

### PR DESCRIPTION
**Pull request by abhi-agg**
Fixes https://mozilla-hub.atlassian.net/browse/DENG-3248

### CODE REVIEW

**Comment by abhi-agg** [comment]
After running `serve build forecast:app multiply:app -o serve_config.yaml` command to generate config file, I am getting these warnings:

```
2024-04-04 12:37:14,997	WARNING deployment.py:413 -- DeprecationWarning: `route_prefix` in `@serve.deployment` has been deprecated. To specify a route prefix for an application, pass it into `serve.run` instead.
2024-04-04 12:37:14,999	WARNING deployment.py:413 -- DeprecationWarning: `route_prefix` in `@serve.deployment` has been deprecated. To specify a route prefix for an application, pass it into `serve.run` instead.
```

Looks like their documentation is outdated (as per the [examples here](https://docs.ray.io/en/latest/serve/multi-app.html#getting-started)).

I will try to find a solution for this next.

**Comment by abhi-agg** [comment]
As per [the source code documentation](https://github.com/ray-project/ray/blob/master/python/ray/serve/api.py#L286) and https://github.com/ray-project/ray/issues/31932 and if we still want to [follow best practice](https://docs.ray.io/en/latest/serve/production-guide/best-practices.html#cli-best-practices) (of using `serve build` command to generate config file), the only option that we are left with is to manually update the generated config file to set the right `route_prefix` for each application.

**Comment by Dexterp37** [comment]
> the only option that we are left with is to manually update the generated config file to set the right `route_prefix` for each application.

That's fine. The expectation is to generate the file once to have a template, then it requires manual tweaking anyway

**Comment by abhi-agg** [comment]
I am able to deploy both applications via `serve deploy` command. Just need to test whether both of them perform inference or not.

**Comment by abhi-agg** [comment]
I am able to run the inference on both applications. I will be submitting changes to README very soon to mark this PR ready for review.

**Comment by chelseatroy** [comment]
It works for me!

Screenshot 2024-04-04 at 11 09 54 AM

Screenshot 2024-04-04 at 11 09 48 AM

**Review by chelseatroy — APPROVED** [review]
I followed the README and was able to visit both applications in my browser, so this PR meets the acceptance criteria. Approved!

I'm relieved to know that a multi-application deployment kinda "just works" with the addition of an application class and then a `serve_config` block to route it up.

**Pull request merged**
